WebApp/Controllers/ViewSwitcherController.cs
using System.Web.Mvc;
using System.Web.WebPages;

namespace WebApp.Controllers
{
    public class ViewSwitcherController : Controller
    {
        public RedirectResult SwitchView(bool mobile, string returnUrl) {
            if (Request.Browser.IsMobileDevice == mobile)
                HttpContext.ClearOverriddenBrowser();
            else
                HttpContext.SetOverriddenBrowser(mobile ? BrowserOverride.Mobile : BrowserOverride.Desktop);

            return Redirect(returnUrl);
        }
    }
}

WebApp/Views/Shared/_Layout.Mobile.cshtml
<!DOCTYPE html> 
<html> 
    <head> 
        <meta charset="utf-8" />
        <title>@ViewBag.Title</title> 
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/Mobile/css", "~/Content/jquerymobile/css")
        @Scripts.Render("~/bundles/jquery", "~/bundles/jquerymobile")
        <script>
            $(document).ready(function () {
                $.mobile.ajaxEnabled = false; 
            });
        </script>
        @RenderSection("head", false)
    </head> 
<body> 

    <div data-role="page" data-theme="a">
        @Html.Partial("_ViewSwitcher")

        <div data-role="header">
            <h1>@ViewBag.Title</h1>
        </div>

        <div data-role="content">
            @RenderSection("featured", false)
            @RenderBody()		
        </div>

    </div>
    @RenderSection("scripts", false)
</body>
</html>

WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale = 1.0, maximum-scale=1.0, user-scalable=no" />
    <title>@ViewBag.Title</title>
    <link rel="shortcut icon" href="~/Content/favicon.ico" />
    @Styles.Render("~/bundles/css")
    @Scripts.Render("~/bundles/modernizr")
    @RenderSection("head", required: false)
    <style type="text/css">
        .search {
            display: inline-flex;
        }

        .fields {
            width: 75%;
            float: left;
            display: inline;
        }

            .fields input {
                float: right;
                border: 0;
                border-radius: 7px;
                padding: 0 17px;
                border-bottom: 5px solid #bdc3c7;
                height: 30px;
                font-family: 'Roboto',sans-serif;
                color: #7f8c8d;
                font-size: 19px;
                margin-top: 5px;
                margin-left: 5px;
            }

        #login img {
            top: -4px;
            display: inline-block;
            position: relative;
        }

        .loginbuttons {
            top: 5px;
            position: relative;
            float: left;
        }

            .loginbuttons img {
                width: 30px;
            }



        /* Container */
        .container-fluid {
            z-index: 1;
            background: #FFFFFF;
            margin: 40px auto 10px;
            padding: 20px 40px 0;
            max-width: 960px;
            box-shadow: 0 1px 1px rgba(0, 0, 0, 0.1);
            position: relative;
        }


        /* Page Header */
        .page-header {
            background: #f9f9f9;
            margin: -30px -40px 40px;
            padding: 20px 40px;
            border-top: 4px solid #ccc;
            color: #999;
            text-transform: uppercase;
        }

            .page-header h3 {
                line-height: 0.88rem;
                color: #000;
            }



        /* Thumbnail Box */
        .caption h4 {
            font-size: 1rem;
            color: #444;
        }

        .caption p {
            font-size: 0.75rem;
            color: #999;
        }

        .btn.btn-mini {
            font-size: 0.63rem;
        }


        /* Carousel Control */
        .control-box {
            text-align: right;
            width: 100%;
        }

        .carousel-control {
            background: #666;
            border: 0px;
            border-radius: 0px;
            display: inline-block;
            font-size: 34px;
            font-weight: 200;
            line-height: 18px;
            opacity: 0.5;
            padding: 4px 10px 0px;
            position: static;
            height: 30px;
            width: 15px;
        }


        /* Mobile Only */
        @@media (max-width: 767px) {
            .page-header, .control-box {
                text-align: center;
            }
        }

        @@media (max-width: 479px) {
            .caption {
                word-break: break-all;
            }
        }


        /* ADD-ON
-------------------------------------------------- */
        body:after {
            content: "less than 320px";
            font-size: 1rem;
            font-weight: bold;
            position: fixed;
            bottom: 0;
            width: 100%;
            text-align: center;
            background-color: hsla(1,60%,40%,0.7);
            color: #fff;
            height: 20px;
            padding-top: 0;
            margin-left: 0;
            left: 0;
        }

        @@media only screen and (min-width:320px) {
            body:after {
                content: "320 to 480px";
                background-color: hsla(90,60%,40%,0.7);
                height: 20px;
                padding-top: 0;
                margin-left: 0;
            }
        }

        @@media only screen and (min-width:480px) {
            body:after {
                content: "480 to 768px";
                background-color: hsla(180,60%,40%,0.7);
                height: 20px;
                padding-top: 0;
                margin-left: 0;
            }
        }

        @@media only screen and (min-width:768px) {
            body:after {
                content: "768 to 980px";
                background-color: hsla(270,60%,40%,0.7);
                height: 20px;
                padding-top: 0;
                margin-left: 0;
            }
        }

        @@media only screen and (min-width:980px) {
            body:after {
                content: "980 to 1024px";
                background-color: hsla(300,60%,40%,0.7);
                height: 20px;
                padding-top: 0;
                margin-left: 0;
            }
        }

        @@media only screen and (min-width:1024px) {
            body:after {
                content: "1024 and up";
                background-color: hsla(360,60%,40%,0.7);
                height: 20px;
                padding-top: 0;
                margin-left: 0;
            }
        }

        ::selection {
            background: #ff5e99;
            color: #FFFFFF;
            text-shadow: 0;
        }

        ::-moz-selection {
            background: #ff5e99;
            color: #FFFFFF;
        }

        a, a:focus, a:active, a:hover, object, embed {
            outline: none;
        }

        :-moz-any-link:focus {
            outline: none;
        }

        input::-moz-focus-inner {
            border: 0;
        }

    </style>
</head>
<body>
    <!--[if lt IE 7]>
            <p class="chromeframe">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">activate Google Chrome Frame</a> to improve your experience.</p>
        <![endif]-->
    <header>
        <a href="/" style="text-decoration: none;"><h1>Javascript Games!</h1></a>
        <div class="righthead">
            <div class="search">
                <div class="searchterm">
                    <input type="text" class="srchFld" placeholder="buscar.." />
                    <div class="entypo-search ico"></div>
                </div>
                @if (Request.IsAuthenticated)
                {
                    <a id="logout" href="javascript:void(0)"><img src="~/Content/img/logout.png" /></a>
                }
                else
                {
                    <a id="login" href="javascript:void(0)"><img src="~/Content/img/login.png" /></a>
                }
            </div>
            <div class="login" style="display:none;">
                <div class="fields">
                    <input id="user" name="user" type="text" placeholder="Usuario">
                    <input id="password" name="password" type="password" placeholder="Clave">
                </div>
                <div class="loginbuttons">
                    <a id="loginnext" href="#"><img src="~/Content/img/next.png" /></a>
                    <a id="loginstop" href="#"><img src="~/Content/img/stop.png" /></a>
                </div>
                <div style="clear:left;"></div>
            </div>
        </div>
        @*@Html.Partial("_LoginPartial")*@
    </header>
    <nav id="menu" class="nav">
        <ul>
            <li>
                <a href="@Url.RouteUrl("Games")">
                    <span class="icon">
                        <img src="~/Content/img/super.png" />
                    </span>
                    <span>Juegos</span>
                </a>
            </li>
            <li>
                <a href="@Url.RouteUrl("Developers")">
                    <span class="icon">
                        <img src="~/Content/img/developer.png">
                    </span>
                    <span>Desarrolladores</span>
                </a>
            </li>
            <li>
                <a href="#">
                    <span class="icon">
                        <img src="~/Content/img/job.png">
                    </span>
                    <span>Trabajos</span>
                </a>
            </li>
            <li>
                <a href="#">
                    <span class="icon">
                        <img src="~/Content/img/company.png">
                    </span>
                    <span>Empresas</span>
                </a>
            </li>
            <li>
                <a href="@Url.RouteUrl("ContactUs")">
                    <span class="icon">
                        <img src="~/Content/img/message.png">
                    </span>
                    <span>Contáctenos</span>
                </a>
            </li>
            <li>
                @if (Request.IsAuthenticated)
                {
                    <a href="">
                        <span class="icon">
                            <img src="~/Content/img/home.png">
                        </span>
                        <span>Mi Cuenta</span>
                    </a>
                }
                else
                {
                    <a href="@Url.Action("Register", "Account")">
                        <span class="icon">
                            <img src="~/Content/img/register.png">
                        </span>
                        <span>Registrarse</span>
                    </a>
                }
            </li>
        </ul>
    </nav>
    <section id="content">
        <div id="bg"></div>
        @RenderBody()
    </section>
    <footer>
        <div class="right">
            <div id="letter">JS</div>
            <div id="animation">
                <div class="button"></div>
                <div class="button"></div>
                <div class="stick">
                    <div class="topButton"></div>
                    <div class="bottom"></div>
                    <div class="support"></div>
                </div>
                <div class="rubber"></div>
                <div class="base"></div>
            </div>
        </div>
    </footer>
    <div id="wall"></div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/coreJS")
    <script type="text/javascript">
        $(window).load(function () {
            $("#wall").slideUp(1000, "easeInOutSine");
            $("body").niceScroll({ styler: "fb", cursorcolor: "#000", horizrailenabled: false, zindex: 9999 });
        });
        $("#login").on("click", function () {
            $(".righthead").animate({ "right": -$(".righthead").width() + "px" }, "slow", function () {
                $(".search").hide();
                $(".login").show();
                $(".righthead").animate({ "right": "0px" }, "slow");
            });
            return false;
        });
        $("#loginstop").on("click", function () {
            $(".righthead").animate({ "right": -$(".righthead").width() + "px" }, "slow", function () {
                $(".login").hide();
                $(".search").show();
                $(".righthead").animate({ "right": "0px" }, "slow");
            });
            return false;
        });
    </script>
    @RenderSection("scripts", required: false)
</body>
</html>

WebApp/Views/Shared/_ViewSwitcher.cshtml
@if (Request.Browser.IsMobileDevice && Request.HttpMethod == "GET")
{
    <div class="view-switcher ui-bar-a">
        @if (ViewContext.HttpContext.GetOverriddenBrowser().IsMobileDevice)
        {
            @: Displaying mobile view
            @Html.ActionLink("Desktop view", "SwitchView", "ViewSwitcher", new { mobile = false, returnUrl = Request.Url.PathAndQuery }, new { rel = "external" })
        } 
        else 
        {
            @: Displaying desktop view
            @Html.ActionLink("Mobile view", "SwitchView", "ViewSwitcher", new { mobile = true, returnUrl = Request.Url.PathAndQuery }, new { rel = "external" })
        }
    </div>
}